### ISSUE TITLE
加载opencv 失败

### ISSUE THREAD

**Issue by szhansen** [kongqw/KqwFaceDetectionDemo#17]
小米pad 3，安装了OpenCV_3.2.0_Manager_3.20_armeabi.apk，
打开apk还是报 加载opencv失败

**Comment by szhansen** [comment]
OpenCV_3.2.0_Manager_3.20_arm64-v8a.apk

安装这个可以了

**Comment by kongqw** [comment]
👍，写了无需安装Manager的Sample，不忙的时候整理下传上来
