### ISSUE TITLE
怎样使用摄像头拍照功能

### ISSUE THREAD

**Issue by 790396054** [kongqw/KqwFaceDetectionDemo#18]
就是如何用它进行拍照操作。

**Comment by kongqw** [comment]
@790396054 抓取一帧，将Mat转成Bitmap可否满足你的需求？

**Comment by 790396054** [comment]
1.如何抓取一帧？
2.抓取一帧后可以保证摄像头预览画面还是实时预览么？

**Comment by 790396054** [comment]
mCamera.takePicture(null, null, new Camera.PictureCallback() {
            @Override
            public void onPictureTaken(byte[] data, Camera camera) {
                if (callBack != null) {
                    callBack.hasTakePicture(data);
                }
            }
        });

我用 takePicture 方法，抓取照片后，摄像头不预览了，调用 mCamera.startPreview(); 还是不能预览

**Comment by kongqw** [comment]
``` Java
    @Override
    public Mat onCameraFrame(CvCameraViewFrame inputFrame) {
        // 子线程（非UI线程）
        mRgba = inputFrame.rgba();

        // TODO 抓取 mRgba  转 Bitmap

        return mRgba;
    }
```

Mat 转 Bitmap

``` Java
Bitmap bitmap = Bitmap.createBitmap(mat.width(), mat.height(), Bitmap.Config.ARGB_8888);
Utils.matToBitmap(mat, bitmap);
```

**Comment by 790396054** [comment]
解决了，十分感谢
