### ISSUE TITLE
你好，怎样让摄像头快速关闭和打开

### ISSUE THREAD

**Issue by 790396054** [kongqw/KqwFaceDetectionDemo#20]
不想让摄像头长时间开着，所以想在不用的时候关闭，用的时候快速调起摄像头，进行拍照预览

**Comment by kongqw** [comment]
[BaseCameraView.java](https://github.com/kongqw/OpenCVForAndroid/blob/opencv3.2.0/OpenCVLibrary320/src/main/java/com/kongqw/BaseCameraView.java) 已经处理

``` Java
enableView();
disableView();
```

**Comment by 790396054** [comment]
enableView();
disableView();
这两个方法是相机直接 release 了，有没有不 release 的方法，因为在打开时时间会比较长。
比如暂停 mCamera.stopPreview()，这样，打开时直接 mCamera.startPreview()；
这样试了后，暂停就打不开相机的预览了，不知道哪里出了问题
