### ISSUE TITLE
目标跟踪，容易丢失

### ISSUE THREAD

**Issue by Dreamskya** [kongqw/KqwFaceDetectionDemo#24]
目标跟踪的时候，很容易丢失目标，效果不好。期待，大神下次更新。

**Comment by kongqw** [comment]
单纯使用CamShift，受到算法的限制，对颜色的干扰就是比较大的，不过可以结合其他算法一起使用，只不过受到项目原因，现在不方便开放出来，还请见谅啦 😁

**Comment by mmabluesky** [comment]
@kongqw     厉害，膜拜大神
