### ISSUE TITLE
能否标记出特整点？

### ISSUE THREAD

**Issue by PeterXiaoWang** [kongqw/KqwFaceDetectionDemo#5]
大神，现在是主界面中会用绿框标记出人脸，我想在框住的人脸上面标记出特整点，比如说眼睛嘴巴这好实现吗？能否给个思路

**Comment by kongqw** [comment]
在  [CameraFaceDetectionView](https://github.com/kongqw/FaceDetectLibrary/blob/master/openCVLibrary2411/src/main/java/com/kongqw/view/CameraFaceDetectionView.java) 里加载了一个 ‘lbpcascade_frontalface.xml’ ，官方管它叫**级联分类器** ，是检测（解析）人脸最为重要的部分，这个级联分类器是检测人脸的，你可以在官网搜索一下，还有检测眼睛的，检测嘴巴的，检测微笑的等等，应该可以就可以满足你的需求。

**Comment by PeterXiaoWang** [comment]
谢谢了，大神
