### ISSUE TITLE
opencv加载失败

### ISSUE THREAD

**Issue by niezhiyang** [kongqw/KqwFaceDetectionDemo#6]

**Comment by kongqw** [comment]
有安装opencv manager吗？机型？版本？log？

**Comment by songhaonangit** [comment]
hell@NX549J:/data/app/org.opencv.engine-1 $ cd lib
shell@NX549J:/data/app/org.opencv.engine-1/lib $ ls
arm64
d arm64/                                                                      <
shell@NX549J:/data/app/org.opencv.engine-1/lib/arm64 $ ls
libopencv_java3.so



nubia z11miniS android6.0 安装opencv manager后，重启，依旧提示没有安装opencv manager，
